### ISSUE TITLE
Use dye tags instead of just vanilla dyes

### ISSUE THREAD

**Issue by teh-banana** [TobsenD/XTones-Reworked#10]
Basically title. Use `forge:dyes/<color>` instead of the vanilla dye item. This allows it to work with other mods that provide dyes of those colours as well.

Preferably this would be released on 1.20.1 too 😄

**Comment by TobsenD** [comment]
I have this in the newest version. Could backport to 1.20.1 I think you want it in the forge version right?

**Comment by teh-banana** [comment]
Yes please, forge for 1.20.1

**Comment by TobsenD** [comment]
Can be found in https://github.com/TobsenD/XTones-Reworked/releases/tag/1.0.4-F_1.20.1-47.2.0
