### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by litjohn50** [TobsenD/XTones-Reworked#7]
Hi, I love the mod.

Can you make the blocks have connected textures?

**Comment by TobsenD** [comment]
Will take a look, after my vacation. A specific set of Blocks? I think not all will be running great with connected textures like  zkul.

**Comment by TobsenD** [comment]
Hi, I have checked it once. There is no problem to add the dependencies to https://github.com/SuperMartijn642/Fusion, but I would have to create completely new textures.

Since I am not able to do this myself due to lack of skills, I can unfortunately not offer connected textures.
